# Generated by Django 4.1.3 on 2023-05-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_alter_purchase_purchase_date_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AlterField(
            model_name='address',
            name='woreda',
            field=models.CharField(max_length=2),
        ),
    ]
