# Generated by Django 4.1.3 on 2023-05-15 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='seller',
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(default=datetime.date(2023, 5, 15)),
        ),
    ]
